name: Appdata Validation

on:
  workflow_call:

jobs:
  appdata_validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update package list
      run: |
        sudo apt update

    # Command copied from flathub build process
    - name: Validate appdata file
      run: |
        sudo apt install flatpak
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y org.freedesktop.appstream-glib
        flatpak run --env=G_DEBUG=fatal-criticals org.freedesktop.appstream-glib validate ./buildconfig/flatpak/org.tuxemon.Tuxemon.appdata.xml
