name: Build Flatpak

on:
  workflow_call:
    inputs:
      IS_RELEASE:
        required: true
        type: boolean

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.3
      options: --privileged
    steps:
    - name: Show environment variables
      run: >
        echo IS_RELEASE: ${{ inputs.IS_RELEASE }}

    - name: Checkout repository
      uses: actions/checkout@v4
    # https://stackoverflow.com/questions/60916931/github-action-does-the-if-have-an-else
    - name: Determine flatpak release branch
      uses: haya14busa/action-cond@v1
      id: flatpak_release_branch
      with:
        cond: ${{ inputs.IS_RELEASE }}
        if_true: 'stable'
        if_false: 'development'

    - name: Show Flatpak manifest
      run:  |
        ls -R buildconfig/flatpak/
        cat buildconfig/flatpak/org.tuxemon.Tuxemon.yaml

    - name: Build package
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: Tuxemon.flatpak
        manifest-path: buildconfig/flatpak/org.tuxemon.Tuxemon.yaml
        cache: false
        branch: ${{ steps.flatpak_release_branch.outputs.value }}
  
    - name: Prepare Flatpak directory
      run: |
        mkdir -p Tuxemon-x86_64
        mv Tuxemon.flatpak Tuxemon-x86_64/

    - name: Upload Flatpak artifact as a folder
      uses: actions/upload-artifact@v4
      with:
        name: Tuxemon-x86_64
        path: Tuxemon-x86_64/
